CREATE DATABASE Sales ;
USE Sales ;



-- 1. Which category generates highest revenue?
SELECT category, ROUND(SUM(purchase_amount),2) AS highest_revenue
FROM sales 
GROUP BY category
ORDER BY highest_revenue DESC;


-- Are discounts actually increasing purchase value?
SELECT discount_applied,ROUND(SUM(purchase_amount),2) AS Total_revenue, ROUND(AVG(purchase_amount),2) AS Average_sale
FROM Sales 
GROUP BY discount_applied 
ORDER BY Total_revenue DESC;


-- 3. What is the total revenue generated by male and female customer ? 
select gender, ROUND(SUM(purchase_amount),2) AS Total_revenue 
from sales 
GROUP BY gender 
ORDER BY Total_revenue DESC;


-- 4. Which customer used a discount but still spent more then the average purchase amount ?
SELECT  customer_id, purchase_amount, discount_applied
FROM sales
WHERE discount_applied = 'Yes'
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM sales)
LIMIT 10 ;

-- 5. Which are the top/bottom 5 products with the highest average review rating.
SELECT item_purchased, ROUND(AVG(review_rating),2) AS Avg_rating
FROM sales
GROUP BY item_purchased
ORDER BY Avg_rating DESC 
LIMIT 5 ;

SELECT item_purchased,ROUND(AVG(review_rating),2) AS Avg_rating 
FROM sales 
GROUP BY item_purchased 
ORDER BY Avg_rating ASC 
LIMIT 5 ;

-- 6. Average purchase: Standard vs Express shipping
SELECT shipping_type,COUNT(DISTINCT customer_id) AS order_placed, ROUND(AVG(purchase_amount),2) AS Average_purchase
FROM sales 
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type ;
ORDER BY Average_purchase, DESC ;

-- 7. Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(DISTINCT( customer_id)) AS User , ROUND(AVG(purchase_amount),2) AS Avg_purchase, ROUND(SUM(purchase_amount),2) AS Total_purchase
FROM sales
GROUP BY subscription_status
ORDER BY Total_purchase ;

-- 8. Top 5 products with highest discount usage %
SELECT item_purchased, COUNT(item_purchased) AS Total_number_of_times_sold, COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS Times_sold_when_discount_applied, 
	COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) *100.0 / COUNT(*) AS Discount_applied_in_percentange 
FROM sales 
GROUP BY item_purchased 
ORDER BY Discount_applied_in_percentange  DESC
LIMIT 5;

-- 9. Segment customer into new, returning and loyal based on their total number of previous purchase, --and show the count of each segment.
SELECT 
	CASE 
		WHEN previous_purchases = '0' THEN "New Customer"
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
	ELSE 'Loyal Customer'
END AS Customer_segment ,
COUNT(*) AS Customer_count
FROM sales 
GROUP BY Customer_segment ;

-- 10. What are the top 3 most purchased products within each category ?
WITH CTE AS
(
SELECT category ,
	   item_purchased,
	   COUNT(item_purchased) AS most_purchased,
	   ROUND(SUM(purchase_amount),2) AS Purchased_amount,
	   RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC ) AS RNK 
FROM sales
GROUP BY category,item_purchased 
)
SELECT * FROM CTE 
WHERE RNK <= 3;

-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
SELECT
	CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END AS customer_type,
	subscription_status,
	COUNT(*) AS customer_count,
	COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE 
										WHEN previous_purchases > 5 THEN 'Repeat Buyers'
										ELSE 'Normal Buyers'
									END
									) AS percents

FROM sales
GROUP BY CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END,subscription_status ;
    
-- 12. What is the revenue contribution of each age group ?
SELECT 
	CASE
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
	ELSE '51+'
	END AS Age_Group,
    ROUND(SUM(purchase_amount),2) AS Total_revenue
FROM sales 
GROUP BY Age_Group 
ORDER BY Total_revenue DESC ;

SELECT 
    SERVERPROPERTY('MachineName') AS MachineName,
    SERVERPROPERTY('ServerName') AS ServerName,
    SERVERPROPERTY('InstanceName') AS InstanceName;
